### PR TITLE
Feature/add devise

### PR DESCRIPTION
**Pull request by blessedjasonmwanza**
## Feature/add devise

In this UX update;
- Enable users to create an account
- enable the user to login
- Only allow authenticated users to access data
- Collaborate with @Saadat123456 to complete the project developments

### CODE REVIEW

**Review by OLIPLICHE — CHANGES_REQUESTED** [review]
Hi @blessedjasonmwanza , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights

Linter result is green ✔️
 Commit messages are meaningful✔️
 The pull request have a descriptive title telling you what changes are inside ✔️
 The pull request have a short summary describing introduced changes in more detail ✔️

## Required Changes ♻️

- [x] Please, you need to make some changes in your seeds.rb. 
- 
save

- [x] Here are code from your `seeds.rb`. I suggest that you add email as column in your user. Please fix it and submit again


saf



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by blessedjasonmwanza** [comment]
Hi @OLIPLICHE ,

This is not part of the requirements if you check. I just forgot to remove the seed file as now we have to first create user accounts with authentication.

**Comment by OLIPLICHE** [comment]
> Hi @OLIPLICHE ,
> 
> This is not part of the requirements if you check. I just forgot to remove the seed file as now we have to first create user accounts with authentication.

Hi, that was the feedback I got when I ran your App at my end. Please you can move on, the next reviewer will look at it.

**Review by arslanbisharat — APPROVED** [review]
Hi @blessedjasonmwanza,
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error is present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
